apiVersion: 1

datasources:
  - name: ViaIpe PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: viaipe_monitoring
    user: viaipe_user
    secureJsonData:
      password: viaipe_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
    uid: ViaIpe PostgreSQL